name: Update TOC Interface version(s)

on:
  schedule:
    - cron: 0 3 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update TOC Interface version retail
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail
          beta: false
          ptr: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update Interface version
          commit-message: Update Interface version
          branch: interface-version
          delete-branch: true
